source 'https://rubygems.org'

gem 'rails', '>= 4.0.0'
gem 'sqlite3'
gem 'jquery-rails'
gem 'mails_viewer', :path => '../../'
group :assets do
  gem 'sass-rails', ">= 4.0.0"
  gem 'coffee-rails', ">= 4.0.0"
end
